services:
  postgres:
    image: postgres:latest
    container_name: books-postgres-db
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
